### ISSUE TITLE
Keeps timeouting

### ISSUE THREAD

**Issue by effyyx** [lzgirlcat/kitty-mpd-background#1]
Im not sure if you are going to read this but i basically followed the instructions on the github page and it works fine until 10 secounds pass and then it keeps infinitely spamming kitty timed out did i do something wrong or if you have some free time could you help a bit.
![timeout](https://user-images.githubusercontent.com/95172517/208529929-3921b61d-eeac-420d-9cf6-a25e8ce3a6dd.png)

**Comment by lzgirlcat** [comment]
yeah I've veen facing the same problem after the recent kitty update, I'll edit the script later today to redirect stderr to /dev/null

**Comment by lzgirlcat** [comment]
should be fixed now!
beware i also changed the kitty socket path to `/tmp/kittyncmpcpp` so please redo the setup

**Comment by lzgirlcat** [comment]
i also removed the delay so it should work much faster :)

**Comment by effyyx** [comment]
Thanks works perfectly love it :)
